//this file create an object and we can use this data in any of the files
const constants={
    openWeatherMap:{
        BASE_URL: "https://api.openweathermap.org/data/2.5/weather?q=",
        SECRET_KEY:"08886e49746eeb52ace8f46fa10dec7d"  //api key generated by openweathermap.org
    }
}

module.exports=constants;